project_id = "tucmwxmsoqqrrotygzcn"

[functions.submit-contact]
verify_jwt = false

[functions.enhance-image]
verify_jwt = true

[functions.check-prediction-status]
verify_jwt = true

[functions.generate-runware-image]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.generate-replicate-image]
verify_jwt = true

[functions.manage-user-credits]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.enhance-voice-prompt]
verify_jwt = false
