
project_id = "itkfghwxbodjlmpgydsq"

[functions.generate-runware-image]
verify_jwt = false

[functions.generate-replicate-image]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
