
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { generateDalleImage } from "./openai.ts";
import { logImageGeneration } from "./supabaseClient.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const requestBody = await req.text();
    console.log("Request body:", requestBody);
    const { prompt, n = 1, size = "1024x1024", quality = "standard", apiKey = null, userId = null } = JSON.parse(requestBody);

    let openaiKey = Deno.env.get("OPENAI_API_KEY");
    if (!openaiKey && apiKey) {
      console.log("Using client-provided API key");
      openaiKey = apiKey;
    }

    if (!openaiKey) {
      return new Response(
        JSON.stringify({
          error: true,
          errorMessage: "OpenAI API key not configured",
          errors: [
            {
              code: "API_NOT_FOUND",
              message: "API key not found in environment"
            }
          ]
        }),
        {
          status: 401,
          headers: { ...corsHeaders, "Content-Type": "application/json" }
        }
      );
    }

    if (!prompt || typeof prompt !== "string" || !prompt.trim()) {
      return new Response(
        JSON.stringify({
          error: true,
          errorMessage: "Invalid prompt",
          errors: [
            {
              code: "VALIDATION_ERROR",
              message: "Prompt is required and must be a non-empty string"
            }
          ]
        }),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" }
        }
      );
    }

    // Clean the prompt for DALL-E
    // Remove style tags like [Photorealistic] that may be causing issues
    const cleanedPrompt = prompt.replace(/^\[(.*?)\]\s*/i, '');
    
    // Test prompt for validation purposes
    if (cleanedPrompt.trim().toLowerCase() === "server key check") {
      // If it's just a server key check, return a success message without calling OpenAI
      return new Response(
        JSON.stringify({
          imageUrl: "https://via.placeholder.com/1024x1024?text=Server+Key+Valid",
          usingServerKey: true,
          metadata: { model: "server-check", promptId: "test-check", size: size, createdAt: new Date().toISOString() }
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Enforce daily limit for free users: 1 image per day
    if (userId) {
      try {
        const now = new Date();
        const startOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString();
        const endOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1).toISOString();

        // Query to count number of images generated by user today under 'free' plan
        const countRes = await fetch(`${SUPABASE_URL}/rest/v1/image_generations?user_id=eq.${userId}&created_at=gte.${startOfDay}&created_at=lt.${endOfDay}&plan=eq.free&select=id`, {
          method: "HEAD",
          headers: {
            apikey: SUPABASE_SERVICE_ROLE_KEY!,
            Authorization: `Bearer ${SUPABASE_SERVICE_ROLE_KEY!}`,
            Accept: "application/json",
          },
        });

        if (!countRes.ok) {
          console.error("Failed to count image generations for user", await countRes.text());
          return new Response(
            JSON.stringify({
              error: true,
              errorMessage: "Failed to verify usage limit",
              errors: [{ code: "API_ERROR", message: "Failed to verify usage limit" }]
            }),
            { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
          );
        }

        // The count is in the Content-Range header for HEAD request.
        // Format of Content-Range: items start-end/total
        const range = countRes.headers.get("content-range");
        // Parse total from content-range header
        let totalCount = 0;
        if (range) {
          const parts = range.split("/");
          if (parts.length === 2) {
            totalCount = parseInt(parts[1], 10);
          }
        }

        if (totalCount >= 1) {
          return new Response(
            JSON.stringify({
              error: true,
              errorMessage: "Free plan users can generate only 1 image per day. Please upgrade your plan for more.",
              errors: [{ code: "LIMIT_EXCEEDED", message: "Daily generation limit reached" }]
            }),
            { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
          );
        }
      } catch (err) {
        console.error("Error checking daily limit:", err);
        return new Response(
          JSON.stringify({
            error: true,
            errorMessage: "Unexpected error during usage check",
            errors: [{ code: "RUNTIME_ERROR", message: "Unexpected error during usage check" }]
          }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
    }

    console.log("Processing DALL-E 3 image generation request:", {
      prompt: cleanedPrompt.substring(0, 30) + "...",
      size,
      quality,
      n,
      userId: userId || "anonymous"
    });

    let data;
    try {
      data = await generateDalleImage({
        prompt: cleanedPrompt, // Use the cleaned prompt
        n,
        size,
        quality,
        openaiKey
      });
    } catch (err) {
      console.error("OpenAI API Error:", err);

      let code = "API_ERROR";
      let msg = "Failed to generate image";
      let errorType = undefined;

      if (err.isOpenAI && err.errorData?.error?.type) {
        errorType = err.errorData.error.type;
        msg = err.errorData.error.message || msg;
        if (errorType === "invalid_request_error") {
          code = err.errorData.error.param === "api_key" ? "INVALID_API_KEY" : "VALIDATION_ERROR";
        } else if (err.response?.status === 429) {
          code = "RATE_LIMIT";
        }
      }

      return new Response(
        JSON.stringify({
          error: true,
          errorMessage: msg,
          errors: [
            {
              code,
              message: msg,
              details: errorType
            }
          ]
        }),
        {
          status: err.response?.status || 500,
          headers: { ...corsHeaders, "Content-Type": "application/json" }
        }
      );
    }

    if (!data.data?.[0]?.url) {
      return new Response(
        JSON.stringify({
          error: true,
          errorMessage: "No image URL received from OpenAI",
          errors: [
            {
              code: "API_ERROR",
              message: "Invalid response format"
            }
          ]
        }),
        {
          status: 500,
          headers: { ...corsHeaders, "Content-Type": "application/json" }
        }
      );
    }

    const promptId = crypto.randomUUID();
    const createdAt = new Date().toISOString();
    const metadata = {
      model: "dall-e-3",
      promptId,
      size: size,
      createdAt,
      userId: userId || undefined
    };

    if (SUPABASE_URL && SUPABASE_SERVICE_ROLE_KEY) {
      await logImageGeneration({
        SUPABASE_URL,
        SUPABASE_SERVICE_ROLE_KEY,
        data: {
          user_id: userId,
          prompt: cleanedPrompt, // Store the cleaned prompt
          image_url: data.data[0].url,
          size,
          model: "dall-e-3",
          quality,
          prompt_id: promptId,
          created_at: createdAt,
          plan: 'free' // Record the plan used; 'free' assumed here, could be upgraded with later logic
        }
      });
    }

    return new Response(
      JSON.stringify({
        imageUrl: data.data[0].url,
        usingServerKey: !apiKey,
        metadata: metadata
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" }
      }
    );
  } catch (error) {
    console.error("Edge function error:", error.stack || error);
    return new Response(
      JSON.stringify({
        error: true,
        errorMessage: error.message || "An unexpected error occurred",
        errors: [
          {
            code: "RUNTIME_ERROR",
            message: error.message || "Unknown error"
          }
        ]
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" }
      }
    );
  }
});
